### PR TITLE
Update ReadMe.md to add feature details

### PR DESCRIPTION
**Pull request by DanRStevens**
Also updated supported compiler list.

Feel free to adjust. I just thought I'd get a start on it.

### CODE REVIEW

**Comment by DanRStevens** [comment]
Hmm, thinking about those references to other libraries, you're right that we could probably come up with something better. I think the first paragraph should focus on what the library is, rather than what it is not. I seem to have set a negative description with the two references I added.

Perhaps in the following paragraphs we could add the details about related repositories, or about other repositories the user may have been looking for.

This also raises the question, how clear is the repository name? Could we do better? I can't think of anything better. Though if we're feeling the need to explain what something is and what it is not, perhaps the repository name is the real issue.

**Comment by DanRStevens** [comment]
I wonder if "OP2Resources" might be a better name for this repository. That might also help set the scope of the library.

----

I'm fine with removing the change log, if you want to do that. We really haven't been tracking changes well for this project, so the only real way to get changes is through the project commit history.

**Comment by Brett208** [comment]
I tried to condense some of your thoughts in a final edit. Hopefully it reads better? I think we should probably merge this soon instead of continuing to edit.

I would be okay switching the name to OP2Resources. It is a bit more specific than OP2Utility. However, that would be a lot of work renaming files, updating project files, and repo name and we would lose the momentum in the forums of the old name. I'm not looking to take that on right now myself (lazy I suppose).

**Comment by DanRStevens** [comment]
Definitely reads better now.

The repository name can be addressed another time.

**Pull request merged**
