### PR TITLE
Move op2 utility.h into directory include

### PR DESCRIPTION
**Pull request by Brett208**
- Update line endings in OP2Utility to be standardized as CRLF again 
 - Move library wide header OP2Utility.h into new subdirectory /include 
 - Update OP2Utility.h to include all pertinent header files 
 - Update introductory comments in OP2Utility.h

### CODE REVIEW

**Comment by Brett208** [comment]
Good to hear the careful commits paid off.

I have not pinpointed when those 11 files had their line endings changed. It must have been a commit dealing with the archive and stream code, or a couple of commits. I did check the original files from the subversion repo, and they were CRLF. I'm not too concerned with tracking the blame down. I'm just going to be more careful to watch for it in the future so we don't do it again. Turns out VS was changing its project files back to CRLF on me automatically even though I had leashed Git to keep it from changing them to LF only. So that is why I was having so much trouble pinpointing the issue. VS would make them CRLF and then Git would make them LF in a nice cycle. I think VS may have only been changing the project files to CRLF and not the source code to make it more confusing. I would need to play with this some more to say for sure though???

I found Notepad++ made it easy to find the offending files and then fix them.

I was planning to move to the source directory on the next branch I open up. This branch's title doesn't really cover it. 

I guess the presence or lack of presence of extra white space doesn't really bother me. I'd like to commit this branch. Then when we move the source code if you want to jump in with an additional commit to fix the extraneous white space I wouldn't mind. That branch will touch all the source code outside of OP2Utility.h anyways and be a nice time to fix it.

Also, I want to get the header code merged so I can fix OP2Archive and OP2MapImager to point to the new header file location to make testing easier on my part.

Thanks,
Brett

**Comment by DanRStevens** [comment]
I checked out the commit that supposedly normalized line endings to CRLF. The files modified in that commit are the only ones in the repo with CRLF endings. All the rest still have LF endings.
```
~/code/opu/OP2Utility$ file * */*
Archives:                       directory
License.txt:                    ASCII text
makefile:                       makefile script, ASCII text
Maps:                           directory
OP2Utility.h:                   C source, ASCII text, with CRLF line terminators
OP2Utility License - MIT.txt:   ASCII text, with very long lines
OP2Utility.sln:                 UTF-8 Unicode (with BOM) text
OP2Utility.vcxproj:             XML 1.0 document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
OP2Utility.vcxproj.filters:     XML 1.0 document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
ReadMe.md:                      ASCII text
ResourceManager.cpp:            C source, ASCII text
ResourceManager.h:              C++ source, ASCII text
Streams:                        directory
StringHelper.cpp:               C source, ASCII text
StringHelper.h:                 C++ source, ASCII text
XFile.cpp:                      C source, ASCII text
XFile.h:                        C source, ASCII text
Archives/AdaptHuffTree.cpp:     C source, ASCII text
Archives/AdaptHuffTree.h:       ASCII text
Archives/ArchiveFile.h:         C source, ASCII text
Archives/ArchivePacker.cpp:     C source, ASCII text, with CRLF line terminators
Archives/ArchivePacker.h:       C source, ASCII text, with CRLF line terminators
Archives/ArchiveUnpacker.cpp:   C source, ASCII text, with CRLF line terminators
Archives/ArchiveUnpacker.h:     C++ source, ASCII text, with CRLF line terminators
Archives/BitStream.cpp:         C source, ASCII text
Archives/BitStream.h:           ASCII text
Archives/ClmFile.cpp:           C source, ASCII text, with CRLF line terminators
Archives/ClmFile.h:             C source, ASCII text
Archives/CompressionType.h:     ASCII text
Archives/HuffLZ.cpp:            C source, ASCII text
Archives/HuffLZ.h:              C source, ASCII text
Archives/VolFile.cpp:           C source, ASCII text, with CRLF line terminators
Archives/VolFile.h:             C source, ASCII text
Archives/WaveFile.h:            C source, ASCII text
Maps/CellType.h:                ASCII text
Maps/ClipRect.h:                C source, ASCII text
Maps/MapData.cpp:               C source, ASCII text
Maps/MapData.h:                 C++ source, ASCII text
Maps/MapHeader.h:               C source, ASCII text
Maps/MapReader.cpp:             C source, ASCII text
Maps/MapReader.h:               C++ source, ASCII text
Maps/MapWriter.cpp:             C source, ASCII text
Maps/MapWriter.h:               C++ source, ASCII text
Maps/TerrainType.h:             C source, ASCII text
Maps/TileData.h:                C source, ASCII text
Maps/TileGroup.h:               C source, ASCII text
Maps/TileInfo.h:                C source, ASCII text
Maps/TileSetSource.h:           C source, ASCII text
Streams/FileSliceReader.cpp:    C source, ASCII text
Streams/FileSliceReader.h:      C++ source, ASCII text
Streams/FileStreamReader.cpp:   C source, ASCII text
Streams/FileStreamReader.h:     C++ source, ASCII text
Streams/FileStreamWriter.cpp:   C source, ASCII text
Streams/FileStreamWriter.h:     C++ source, ASCII text
Streams/MemoryStreamReader.cpp: C source, ASCII text
Streams/MemoryStreamReader.h:   C++ source, ASCII text
Streams/MemoryStreamWriter.cpp: C source, ASCII text
Streams/MemoryStreamWriter.h:   C++ source, ASCII text
Streams/SeekableStreamReader.h: C++ source, ASCII text
Streams/SeekableStreamWriter.h: C++ source, ASCII text
Streams/StreamReader.h:         C++ source, ASCII text
Streams/StreamWriter.h:         C++ source, ASCII text, with CRLF line terminators
```

I'm kind of wondering why these files were singled out now. Was it because these files were being worked on, or was there some confusing tool output that suggested those files had a problem?

**Comment by Brett208** [comment]
I manually checked each sourcecode file using notepad++. These were the only ones that had LF line endings. If one or two files had LF line endings, then I might have just missed it. Since all other files have LF line endings, I think somehow they actually had CRLF line endings on my computer but were not registering as a changed file on GitHub.

I wonder if when set to default auto mode for line endings, GitHub can sometimes not report line ending changes as actually a change? Or does it automatically switch them to CRLF on my computer and then back to LF when I commit or something in auto mode?

-Brett

**Comment by DanRStevens** [comment]
Hmm, did you change the `autocrlf` setting recently? Maybe a change in settings accounts for the discrepancy. Especially if some files were already checked out with old settings, while others were checked out with new settings.

With the auto setting, on Windows, it may convert `LF` -> `CRLF` upon checkout, and then converts back `CRLF` -> `LF` upon checkin. That might also be why most stuff in the repository is `LF`, why we've never really noticed a discrepancy before, and why local files may have appeared as `CRLF`.

Things seemed to be working before. Perhaps using `autocrlf=true` for you is an appropriate and convenient option.

Maybe the change reporting behaviour is different from how I remember it, or has changed over the years. It used to be that auto EOL changes showed up in git status as a modification, but nothing was listed by a git diff.

I'm still a little uncertain what happened that caused you to check. Was git status showing changed files that didn't seem to have any changes? Was git diff showing the entire file changed unexpectedly? Or did you just happen to notice the editor reported line endings differently for two files? I suppose a few days later, it might be hard to remember the exact thing that caught your attention.

**Pull request merged**
